default: &default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000
  username: <%= ENV.fetch("DB_USERNAME", ENV["USER"]) %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: tree-recycle-development

test:
  <<: *default
  database: tree-recycle-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
